# Generated by Django 3.2.3 on 2021-06-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodyapp', '0005_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.FloatField(default=-1, editable=False),
        ),
    ]
